"""
agents/query_agent.py — LLM-Driven Data Query & Tool Generator Sub-Agent

Single Responsibility:
  - Takes user prompt and classified intent from car_agent (Main Orchestrator)
  - Uses Gemini LLM to dynamically generate DB tool calls and arguments
  - Executes the LLM-generated tool calls against tools/car_tools.py & fuzzy_queries.py
  - Returns the fetched database context string to car_agent for specialist consumption
"""

from __future__ import annotations

import asyncio
from typing import Optional, Any

from pydantic_ai import Agent
from models.schemas import QueryPlan, FuzzyCarFilter, LLMToolPlan, ExtractedEntities, ToolCall
from tools.car_tools import (
    get_all_cars,
    get_service_intervals,
    get_common_issue_info,
    format_cars_for_context,
)
from db.fuzzy_queries import fuzzy_engine


# ─────────────────────────────────────────────
# LLM DB Tool Generator System Prompt
# ─────────────────────────────────────────────

QUERY_TOOL_GENERATOR_PROMPT = """You are AutoBot's LLM Data Query Generator Sub-Agent.

Your job: Analyze the user's prompt and classified intent, then specify which Database Tools to invoke and what argument parameters to pass to them.

AVAILABLE DATABASE TOOLS:
1. filter_cars_by_budget : max_budget (float, in lakhs)
2. filter_cars_by_fuel   : fuel_type (EV, Petrol, Diesel, CNG, Hybrid)
3. filter_cars_by_segment: segment (SUV, Sedan, Hatchback, MPV, MUV)
4. get_car_by_name       : car_name (str)
5. get_common_issue_info : issue_keyword (str)
6. get_service_intervals : car_name (str or null)

Extract relevant entities from the user message (budget, fuel type, segment, car name, issue keyword, price, interest rate, tenure).
Select the appropriate tools based on the intent and provide a one-sentence reasoning for your choices.
"""


def _execute_llm_tool_plan(plan_data: dict, intent: str, user_message: str) -> tuple[str, QueryPlan]:
    """Execute the DB tool calls generated by the LLM in query_agent."""
    tools_to_run = plan_data.get("tools_to_run", [])
    entities = plan_data.get("extracted_entities", {})
    reasoning = plan_data.get("reasoning", "LLM-generated DB tool execution plan")

    fuzzy_filter = FuzzyCarFilter(
        budget_lakh_max=entities.get("budget_lakh") or entities.get("price_lakh"),
        fuel_type=entities.get("fuel_type"),
        segment=entities.get("segment"),
        min_seating=entities.get("min_seating"),
        car_name_query=entities.get("car_name"),
        issue_keyword=entities.get("issue_keyword"),
    )

    query_plan = QueryPlan(
        intent=intent,  # type: ignore[arg-type]
        filters=fuzzy_filter,
        sort_by="relevance",
        max_results=5,
        reasoning=reasoning,
        emi_price_lakh=entities.get("price_lakh") or entities.get("budget_lakh"),
        emi_interest_rate=entities.get("interest_rate"),
        emi_tenure_years=entities.get("tenure_years"),
    )

    context_lines = []

    # Execute intent-specific fuzzy & tool queries based on LLM tool plan
    if intent == "recommend":
        all_cars = get_all_cars()
        matched = fuzzy_engine.search_cars(query_plan, all_cars)
        context_lines.append("[MATCHED CARS] LLM Query Plan DB Results:\n" + format_cars_for_context(matched))

    elif intent == "diagnostic":
        issue_kw = entities.get("issue_keyword") or user_message
        issue = get_common_issue_info(issue_kw)
        if not issue:
            from db.queries import db_get_all_issues
            all_issues = db_get_all_issues()
            issue = fuzzy_engine.search_issue(issue_kw, all_issues)
        if issue:
            context_lines.append(f"[MATCHED ISSUE] {issue}")

    elif intent == "service":
        intervals = get_service_intervals()
        car_name = entities.get("car_name", "")
        search_kw = f"{car_name} {user_message}".strip()
        relevant = fuzzy_engine.search_service(search_kw, intervals)
        context_lines.append(f"[MATCHED SERVICE] Intervals:\n{relevant}")

    db_context_str = "\n\n".join(context_lines)
    return db_context_str, query_plan


_cached_query_agent: Optional[Agent[Any, LLMToolPlan]] = None


def _get_query_agent(model: Any) -> Agent[Any, LLMToolPlan]:
    """Singleton Pydantic AI query agent with LLMToolPlan output type."""
    global _cached_query_agent
    if _cached_query_agent is not None:
        return _cached_query_agent
    _cached_query_agent = Agent(
        model,
        output_type=LLMToolPlan,
        system_prompt=QUERY_TOOL_GENERATOR_PROMPT,
    )
    return _cached_query_agent


async def run_query_agent(
    user_message: str,
    intent: str = "recommend",
    api_semaphore: Optional[asyncio.Semaphore] = None,
    model: Any = None,
) -> tuple[str, QueryPlan]:
    """
    Data Query Sub-Agent Entry Point:
      1. Uses Pydantic AI Agent to generate dynamic DB tool calls & arguments (LLMToolPlan output)
      2. Executes generated tools against DB/fuzzy queries
      3. Returns (db_context_string, query_plan)
    """
    if model is None:
        # Static rule fallback when no model provided
        plan_data = {
            "tools_to_run": [{"tool": "filter_cars_by_budget", "args": {}}],
            "extracted_entities": {},
            "reasoning": "Fallback tool generator",
        }
        return _execute_llm_tool_plan(plan_data, intent, user_message)

    try:
        prompt = (
            f"CLASSIFIED INTENT: {intent}\n"
            f"USER MESSAGE: {user_message}"
        )
        if api_semaphore:
            async with api_semaphore:
                res = await _get_query_agent(model).run(prompt)
        else:
            res = await _get_query_agent(model).run(prompt)

        plan: LLMToolPlan = res.output

        # Convert Pydantic LLMToolPlan to the dict format expected by _execute_llm_tool_plan
        plan_data = {
            "tools_to_run": [{"tool": tc.tool, "args": tc.args} for tc in plan.tools_to_run],
            "extracted_entities": plan.extracted_entities.model_dump(),
            "reasoning": plan.reasoning,
        }

        print(f"🧠 [QUERY AGENT LLM TOOLS] Generated tool plan: {plan_data.get('tools_to_run')} | reasoning={plan.reasoning}")
        return _execute_llm_tool_plan(plan_data, intent, user_message)

    except Exception as e:
        print(f"⚠️ [QUERY AGENT] LLM tool plan generation failed ({e}) — using default plan")
        plan_data = {
            "tools_to_run": [{"tool": "filter_cars_by_budget", "args": {}}],
            "extracted_entities": {},
            "reasoning": "Fallback tool generator",
        }
        return _execute_llm_tool_plan(plan_data, intent, user_message)
