"""
Pydantic Models for AutoBot - Structured Data Schemas
"""
from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Literal, Optional, Any


# ─────────────────────────────────────────────
# Routing / Orchestrator Models
# ─────────────────────────────────────────────

class RoutingDecision(BaseModel):
    """
    Pydantic AI output type for the Master Orchestrator multi-intent routing agent.
    Replaces manual JSON parsing to support single and parallel multi-intent routing.
    """
    intents: list[str] = Field(
        default_factory=lambda: ["recommend_cars"],
        description=(
            "List of one or more tool/intent names to route to. "
            "Possible items: recommend_cars, diagnose_vehicle, get_service_schedule, calculate_emi, answer_general"
        )
    )
    reason: str = Field(
        default="",
        description="Brief explanation of why these tools were selected"
    )


class MultiIntentResult(BaseModel):
    """Container aggregating structured output results from parallel sub-agents."""
    intents: list[str] = Field(description="List of executed intents")
    results: dict[str, Any] = Field(description="Map of intent -> Pydantic response object")


# ─────────────────────────────────────────────
# Query Agent Models
# ─────────────────────────────────────────────

class ExtractedEntities(BaseModel):
    """Entities extracted from the user message by the Query Agent LLM."""
    budget_lakh: Optional[float] = Field(default=None, description="Budget in lakhs")
    fuel_type: Optional[str] = Field(default=None, description="Fuel type preference")
    segment: Optional[str] = Field(default=None, description="Car segment preference")
    min_seating: Optional[int] = Field(default=None, description="Minimum seat count")
    car_name: Optional[str] = Field(default=None, description="Specific car name")
    issue_keyword: Optional[str] = Field(default=None, description="Diagnostic issue keyword")
    price_lakh: Optional[float] = Field(default=None, description="Car price in lakhs (for EMI)")
    interest_rate: Optional[float] = Field(default=None, description="Loan interest rate %")
    tenure_years: Optional[int] = Field(default=None, description="Loan tenure in years")


class ToolCall(BaseModel):
    """A single DB tool call generated by the Query Agent LLM."""
    tool: str = Field(description="Tool name to invoke")
    args: dict[str, Any] = Field(default_factory=dict, description="Arguments to pass to the tool")


class LLMToolPlan(BaseModel):
    """
    Pydantic AI output type for the Query Agent.
    Replaces the manual JSON parsing of the raw genai.Client DB tool plan call.
    """
    tools_to_run: list[ToolCall] = Field(
        default_factory=list,
        description="List of DB tools to invoke with their arguments"
    )
    extracted_entities: ExtractedEntities = Field(
        default_factory=ExtractedEntities,
        description="Key entities extracted from the user message"
    )
    reasoning: str = Field(
        default="",
        description="Why the Query Agent chose these tools and parameters"
    )



# ─────────────────────────────────────────────
# Query Plan Models (Dynamic Query Generation)
# ─────────────────────────────────────────────

IntentType = Literal["recommend", "diagnostic", "service", "emi", "general"]
SortByOption = Literal["price_asc", "price_desc", "mileage_desc", "seating_desc", "relevance"]

class FuzzyCarFilter(BaseModel):
    """
    A set of filter parameters with fuzzy tolerances.
    The fuzzy query executor uses these to do soft matching
    instead of exact SQL equality / range constraints.
    """
    # Budget — fuzzy: ±20% of stated budget
    budget_lakh_min: Optional[float] = Field(
        default=None,
        description="Minimum price in lakhs (fuzzy lower bound)"
    )
    budget_lakh_max: Optional[float] = Field(
        default=None,
        description="Maximum price in lakhs (fuzzy upper bound, with tolerance)"
    )
    budget_tolerance_pct: float = Field(
        default=0.20,
        ge=0.0, le=1.0,
        description="How much above budget to still consider (0.20 = 20% stretch)"
    )

    # Fuel type — fuzzy: 'ev' → 'Electric', 'petrol'→'Petrol', etc.
    fuel_type: Optional[str] = Field(
        default=None,
        description="Desired fuel type (raw, will be fuzzy-matched to DB values)"
    )

    # Segment — fuzzy: 'family car' → SUV/MUV, 'small car' → Hatchback
    segment: Optional[str] = Field(
        default=None,
        description="Car segment keyword (fuzzy-matched)"
    )

    # Seating — fuzzy: 5-seater → [4,5,6], 7-seater → [6,7,8]
    min_seating: Optional[int] = Field(
        default=None,
        description="Minimum number of seats required"
    )

    # Transmission preference
    transmission: Optional[str] = Field(
        default=None,
        description="Preferred transmission: Manual, Automatic, CVT, DCT"
    )

    # Car name — fuzzy string match for typos (e.g. 'cretta' → 'Creta')
    car_name_query: Optional[str] = Field(
        default=None,
        description="Specific car name to look up (fuzzy typo-tolerant match)"
    )

    # Features (keywords to match against features array)
    feature_keywords: list[str] = Field(
        default_factory=list,
        description="Feature keywords to match (e.g. sunroof, ADAS, 360 camera)"
    )

    # Issue keyword for diagnostic fuzzy search
    issue_keyword: Optional[str] = Field(
        default=None,
        description="Symptom or issue keyword for fuzzy common_issues lookup"
    )

    # Brand preference
    brand: Optional[str] = Field(
        default=None,
        description="Preferred brand (Maruti, Hyundai, Tata, etc.)"
    )


class QueryPlan(BaseModel):
    """
    Full dynamic query plan generated by the Query Agent from raw user prompt.

    Instead of agents calling hardcoded tool functions, the Query Agent
    analyses the user message and produces this structured plan.
    The fuzzy query executor then executes it against the DB.
    """
    intent: IntentType = Field(
        description="The resolved intent for this query"
    )
    filters: FuzzyCarFilter = Field(
        default_factory=FuzzyCarFilter,
        description="Structured filter parameters for DB query"
    )
    sort_by: SortByOption = "relevance"
    max_results: int = Field(
        default=5,
        ge=1, le=20,
        description="Maximum number of DB results to fetch for context"
    )
    reasoning: str = Field(
        default="",
        description="Why the Query Agent chose these parameters (for logging/debug)"
    )
    # EMI-specific fields
    emi_price_lakh: Optional[float] = Field(
        default=None,
        description="Car price in lakhs for EMI calculation"
    )
    emi_interest_rate: Optional[float] = Field(
        default=None,
        description="Annual interest rate % for EMI"
    )
    emi_tenure_years: Optional[int] = Field(
        default=None,
        description="Loan tenure in years"
    )


# ─────────────────────────────────────────────
# Car Recommendation Models
# ─────────────────────────────────────────────

class CarSpec(BaseModel):
    car_name: str = Field(description="Full name of the car")
    brand: str = Field(description="Car manufacturer/brand")
    price_range: str = Field(description="Price range in INR (e.g., ₹8L - ₹12L)")
    fuel_types: list[str] = Field(description="Supported fuel types (e.g. Petrol, Diesel, EV, CNG, Hybrid)")
    mileage_kmpl: float = Field(description="Mileage in km per litre or km per charge")
    engine_cc: Optional[int] = Field(default=None, description="Engine displacement in CC")
    seating_capacity: int = Field(description="Number of seats")
    transmissions: list[str] = Field(description="Available transmission options (e.g. Manual, Automatic, CVT, DCT)")
    pros: list[str] = Field(description="Key advantages of this car")
    cons: list[str] = Field(description="Key disadvantages of this car")
    match_score: float = Field(ge=0, le=100, description="How well it matches user requirements (0-100)")
    segment: str = Field(description="Car segment e.g. Hatchback, Sedan, SUV, MUV")


class CarRecommendationResponse(BaseModel):
    recommendations: list[CarSpec] = Field(description="List of recommended cars (max 3)")
    summary: str = Field(description="Brief summary of recommendations")
    top_pick: str = Field(description="Name of the best match car")
    buying_tips: list[str] = Field(description="Tips for buying the recommended car")


# ─────────────────────────────────────────────
# Diagnostic Models
# ─────────────────────────────────────────────

class DiagnosticReport(BaseModel):
    symptom_described: str = Field(description="The symptom as described by user")
    possible_causes: list[str] = Field(description="List of possible causes for the symptom")
    most_likely_cause: str = Field(description="The most probable cause")
    severity: Literal["Low", "Medium", "High", "Critical"] = Field(description="Severity level of the issue")
    urgency: str = Field(description="How urgently should this be addressed e.g. Immediately, Within a week")
    estimated_repair_cost: str = Field(description="Estimated cost range for repair in INR")
    can_drive: bool = Field(description="Whether it is safe to drive the car currently")
    diy_possible: bool = Field(description="Whether the user can fix it themselves")
    diy_steps: Optional[list[str]] = Field(default=None, description="Steps if DIY is possible")
    workshop_recommendation: str = Field(description="What to tell the mechanic at the workshop")
    parts_that_may_need_replacement: list[str] = Field(description="Parts that may need to be replaced")


# ─────────────────────────────────────────────
# Service & Maintenance Models
# ─────────────────────────────────────────────

class ServiceItem(BaseModel):
    item_name: str = Field(description="Name of service item e.g. Engine Oil, Air Filter")
    interval_km: int = Field(description="Service interval in km")
    last_done_km: Optional[int] = Field(default=None, description="Odometer reading when last done")
    due_at_km: Optional[int] = Field(default=None, description="Due at this odometer reading")
    status: Literal["OK", "Due Soon", "Overdue", "Unknown"] = Field(description="Current status")
    estimated_cost: str = Field(description="Estimated cost in INR")


class ServiceScheduleResponse(BaseModel):
    car_name: str = Field(description="Name of the car")
    current_mileage: int = Field(description="Current odometer reading")
    service_items: list[ServiceItem] = Field(description="List of service items and their status")
    next_service_due: str = Field(description="When is the next major service due")
    total_estimated_cost: str = Field(description="Total estimated cost for all overdue services")
    important_notes: list[str] = Field(description="Important notes for the car owner")


# ─────────────────────────────────────────────
# EMI & Finance Models
# ─────────────────────────────────────────────

class EMICalculationResponse(BaseModel):
    car_name: str = Field(description="Name of the car")
    on_road_price: str = Field(description="On-road price estimate")
    down_payment: str = Field(description="Down payment amount")
    loan_amount: str = Field(description="Loan amount")
    interest_rate: float = Field(description="Annual interest rate in %")
    tenure_months: int = Field(description="Loan tenure in months")
    monthly_emi: str = Field(description="Monthly EMI amount")
    total_interest: str = Field(description="Total interest paid over loan period")
    total_amount_paid: str = Field(description="Total amount paid including interest")
    affordability_check: str = Field(description="Assessment of affordability based on income")
    tips: list[str] = Field(description="Tips to reduce loan cost")


# ─────────────────────────────────────────────
# General Chat Response Model
# ─────────────────────────────────────────────

class GeneralAutoResponse(BaseModel):
    answer: str = Field(description="The main answer to the user's question")
    category: Literal[
        "General Info",
        "Car Recommendation",
        "Diagnostics",
        "Service & Maintenance",
        "Finance & Insurance",
        "Parts & Accessories",
        "Driving Tips",
        "Traffic & Laws",
        "EV & Future Tech"
    ] = Field(description="Category of the question")
    follow_up_questions: list[str] = Field(description="Suggested follow-up questions for the user")
    confidence: Literal["High", "Medium", "Low"] = Field(description="Confidence level in the answer")
